[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["python312"]
aptPkgs = ["python3-pip", "python3-dev", "build-essential"]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
] 