[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 45
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["python312", "gcc", "python312Packages.pip"]
aptPkgs = [
    "python3-pip",
    "python3-dev",
    "build-essential",
    "libffi-dev",
    "libssl-dev",
    "git"
]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.install]
cmds = ["mkdir -p ./workspace"] 